{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "phi-audit.fullname" . }}
  labels:
    {{- include "phi-audit.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.secretName }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          # Order matters — /api MUST match before / so the dashboard doesn't
          # swallow API calls.
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "phi-audit.api.fullname" . }}
                port: { number: 80 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "phi-audit.dashboard.fullname" . }}
                port: { number: 80 }
{{- end }}
