{{- include "phi-audit.validate" . -}}
{{- if .Values.serviceAccount.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "phi-audit.api.serviceAccountName" . }}
  labels:
    {{- include "phi-audit.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- if .Values.azureWorkloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
    {{- with .Values.serviceAccount.api.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.dashboard.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "phi-audit.dashboard.serviceAccountName" . }}
  labels:
    {{- include "phi-audit.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
  {{- with .Values.serviceAccount.dashboard.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
